services:
  - type: web
    name: auracast
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install; npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
